// Kid-Friendly Definitions for Word Club
// All 221 spelling bee words with simple, one-sentence definitions

const DEFINITIONS = {
    "substantially": "In a large or important amount.",
    "formidable": "Very impressive and somewhat frightening because of size or power.",
    "marquee": "A large sign above the entrance to a theater or hotel.",
    "compunction": "A feeling of guilt or uneasiness about doing something wrong.",
    "hyperventilated": "Breathed too quickly, often from panic or excitement.",
    "onslaught": "A fierce or violent attack.",
    "misanthrope": "A person who dislikes and avoids other people.",
    "cravenly": "In a cowardly way, without courage.",
    "hypocritical": "Pretending to have beliefs or virtues you don't really have.",
    "traumatic": "Very upsetting or disturbing, causing emotional shock.",
    "solemnly": "In a serious and formal manner.",
    "contentious": "Causing or likely to cause disagreement or argument.",
    "ensemble": "A group of musicians, actors, or dancers who perform together.",
    "lye": "A strong chemical used for cleaning or making soap.",
    "lacrosse": "A team sport played with a stick with a net on the end.",
    "cajolery": "The act of persuading someone using flattery or gentle coaxing.",
    "residuals": "Payments made to actors or creators for reruns of their work.",
    "peroxide": "A chemical compound often used to bleach hair or clean wounds.",
    "apocalypse": "A catastrophic event that brings about the end of the world.",
    "barricade": "A barrier built to block a road or entrance.",
    "anonymously": "Done without giving your name.",
    "barrette": "A clip or clasp used to hold hair in place.",
    "junket": "A trip taken by officials at public expense, or a sweet dessert.",
    "Erie": "One of the five Great Lakes in North America.",
    "silhouette": "The dark outline of something seen against a lighter background.",
    "thesaurus": "A book that lists words with similar meanings.",
    "chandelier": "A fancy light fixture that hangs from the ceiling with many bulbs.",
    "concierge": "A hotel employee who helps guests with information and services.",
    "hibiscus": "A tropical plant with large, colorful flowers.",
    "maracas": "Musical instruments that make a rattling sound when shaken.",
    "burpees": "An exercise where you squat, jump back, do a push-up, and jump up.",
    "piccolo": "A small flute that makes high-pitched sounds.",
    "tulle": "A soft, fine fabric often used for ballet tutus and veils.",
    "camphor": "A strong-smelling substance used in medicines and moth balls.",
    "paparazzi": "Photographers who follow famous people to take their pictures.",
    "pogrom": "An organized attack on a particular group of people.",
    "pâtisserie": "A French bakery that specializes in pastries and cakes.",
    "sarsaparilla": "A sweet soft drink flavored with the root of a tropical plant.",
    "cannelloni": "Large tube-shaped pasta usually stuffed with meat or cheese.",
    "bronchitis": "An illness that causes swelling in the breathing tubes of the lungs.",
    "diphtheria": "A serious disease that affects breathing and the throat.",
    "corbels": "Stone or wood supports that stick out from walls to hold up structures.",
    "Kilimanjaro": "The tallest mountain in Africa.",
    "protégé": "A person guided and supported by an older, more experienced person.",
    "maquisards": "French resistance fighters during World War II.",
    "Charolais": "A breed of large white cattle originally from France.",
    "chair": "A piece of furniture with a seat and back for one person.",
    "brass": "A shiny yellow metal made from copper and zinc.",
    "ready": "Prepared and able to do something.",
    "hangdog": "Looking sad, guilty, or ashamed.",
    "padlock": "A detachable lock with a curved bar that snaps into place.",
    "scatter": "To throw or spread things in different directions.",
    "gobble": "To eat quickly and noisily.",
    "eel": "A long, snake-like fish that lives in water.",
    "sizzle": "To make a hissing sound like food cooking in hot oil.",
    "Spanish": "The language spoken in Spain and many Latin American countries.",
    "hornet": "A large wasp that can sting multiple times.",
    "oval": "A shape like a stretched-out circle or egg.",
    "plastic": "A synthetic material that can be molded into many shapes.",
    "mason": "A person who builds with stone or brick.",
    "slander": "False spoken statements that damage someone's reputation.",
    "evergreen": "A tree or plant that keeps its green leaves all year.",
    "decompose": "To break down and rot into simpler parts.",
    "reasons": "Explanations or causes for why something happened.",
    "dismantle": "To take something apart piece by piece.",
    "glance": "A quick look at something.",
    "oath": "A serious promise, often made by placing your hand on a Bible.",
    "sneakers": "Casual athletic shoes with rubber soles.",
    "duets": "Musical pieces performed by two people.",
    "cursive": "A style of handwriting where letters are connected.",
    "pastel": "A soft, pale color or a type of crayon used for drawing.",
    "hype": "Extravagant publicity or exaggerated excitement about something.",
    "nestled": "Settled comfortably or snugly in a protected spot.",
    "mustiness": "A stale, moldy smell often found in old, damp places.",
    "shrouded": "Covered or hidden from view.",
    "moderate": "Average in amount, intensity, or quality; not extreme.",
    "mouthpiece": "The part of a device you put in your mouth, or a spokesperson.",
    "lantern": "A portable light with a protective case around it.",
    "author": "A person who writes books, stories, or articles.",
    "wily": "Clever in a sneaky or cunning way.",
    "veil": "A thin piece of fabric worn to cover the face or head.",
    "redress": "To correct or make up for a wrong that was done.",
    "cruiser": "A type of ship or a police car.",
    "vitally": "In an extremely important or essential way.",
    "burrowed": "Dug a hole or tunnel underground.",
    "pentagon": "A shape with five sides and five angles.",
    "diagram": "A simple drawing that shows how something works or is organized.",
    "scrimmage": "A practice game in sports like football or soccer.",
    "vulgar": "Rude, crude, or lacking good taste.",
    "resign": "To voluntarily leave a job or position.",
    "corrupt": "Dishonest and willing to use power for personal gain.",
    "potency": "The power or strength of something.",
    "quartz": "A hard, shiny mineral often found in rocks.",
    "tournament": "A competition with many players or teams competing for a prize.",
    "agribusiness": "Large-scale farming operated as a business.",
    "clementine": "A small, sweet type of orange that's easy to peel.",
    "signature": "A person's name written in their own handwriting.",
    "influence": "The power to affect or change someone or something.",
    "snorkeling": "Swimming underwater while breathing through a tube.",
    "citadel": "A fortress that protects a city.",
    "achievements": "Things accomplished successfully through effort or skill.",
    "appliances": "Devices or machines designed to do household tasks.",
    "invective": "Insulting or abusive language.",
    "badminton": "A game played with rackets and a shuttlecock over a net.",
    "gardenia": "A plant with fragrant white or yellow flowers.",
    "emphatically": "In a forceful, clear way that shows strong feeling.",
    "absorption": "The process of taking something in or soaking it up.",
    "prognosticate": "To predict what will happen in the future.",
    "Pacific": "The largest ocean on Earth, between Asia and the Americas.",
    "affiliation": "A connection or association with a group or organization.",
    "synopsis": "A brief summary of a story or event.",
    "coriander": "An herb with a fresh, citrusy flavor used in cooking.",
    "purgatory": "A place or state of temporary punishment or suffering.",
    "torpor": "A state of being inactive or sluggish.",
    "covetous": "Having a strong desire for something that belongs to someone else.",
    "oppression": "Cruel or unfair treatment by those in power.",
    "abysmal": "Extremely bad or terrible.",
    "precipice": "A very steep cliff or dangerous situation.",
    "purview": "The range or scope of something's authority or concern.",
    "suburbia": "The residential areas on the outskirts of a city.",
    "construe": "To interpret or understand something in a particular way.",
    "fettle": "A person's state of health or spirits.",
    "curriculum": "The subjects and content taught in a school or course.",
    "deuce": "A tie score in tennis, or the number two on dice or cards.",
    "berth": "A sleeping place on a ship or train, or a ship's parking spot.",
    "cyst": "A sac filled with fluid that forms in the body.",
    "knavery": "Dishonest or crafty behavior.",
    "synonym": "A word that means the same or nearly the same as another word.",
    "purloined": "Stolen, especially in a sneaky way.",
    "delectation": "Great pleasure or delight.",
    "austerity": "Living in a simple way without luxury or excess.",
    "nascent": "Just beginning to exist or develop.",
    "extremophile": "An organism that lives in extremely harsh conditions.",
    "monolithic": "Large, powerful, and difficult to change.",
    "coven": "A group or gathering of witches.",
    "satisfice": "To accept something that's good enough rather than perfect.",
    "nuptials": "A wedding ceremony.",
    "aquacade": "An elaborate water show with swimming and diving performances.",
    "assuage": "To make an unpleasant feeling less intense.",
    "ballistics": "The science of how projectiles move through the air.",
    "efficacy": "The ability to produce the desired result.",
    "dreidel": "A four-sided spinning top used in a Jewish game.",
    "alacrity": "Quick and cheerful readiness.",
    "elision": "The omission of a sound or syllable when speaking.",
    "sanctimonious": "Acting morally superior to others in an annoying way.",
    "heptathlon": "An athletic contest with seven different track and field events.",
    "tempera": "A type of paint made by mixing colored powders with egg yolk.",
    "mitosis": "The process where a cell divides into two identical cells.",
    "apologia": "A formal written defense of one's opinions or conduct.",
    "mesomorph": "A person with a muscular, athletic body type.",
    "claustrophobia": "An extreme fear of being in small, enclosed spaces.",
    "glissade": "A way of sliding down a snowy slope in a controlled manner.",
    "antebellum": "Existing before a war, especially before the American Civil War.",
    "weir": "A low dam built across a river to control water flow.",
    "sortie": "A mission flown by a military aircraft, or a quick trip out.",
    "compañero": "A companion or friend, in Spanish.",
    "pelota": "A ball game played in Spain and Latin America.",
    "eloge": "A funeral oration or speech praising someone.",
    "mansard": "A type of roof with two slopes on each side.",
    "ramate": "Having branches.",
    "paranephric": "Located near or around the kidney.",
    "tontine": "An investment plan where the last survivor gets all the money.",
    "asyllabia": "The inability to form syllables or words.",
    "velodrome": "A stadium with a banked oval track for bicycle racing.",
    "dysplasia": "Abnormal growth or development of cells or organs.",
    "Columbiad": "A large cannon used during the American Civil War.",
    "terricolous": "Living on or in the ground.",
    "soporiferous": "Causing sleep or drowsiness.",
    "cyclopean": "Gigantic or massive, like something built by mythical giants.",
    "messianic": "Related to a savior or liberator.",
    "Austronesia": "A region of islands in the Pacific and Indian Oceans.",
    "maxillary": "Related to the upper jaw.",
    "Euclidean": "Related to the geometry studied by the ancient Greek mathematician Euclid.",
    "archizoic": "Related to the earliest forms of life on Earth.",
    "aphagia": "The inability to swallow.",
    "persillade": "A French sauce made with parsley and garlic.",
    "capriccio": "A lively piece of music in a free, spontaneous style.",
    "chitin": "A tough substance that forms the outer covering of insects.",
    "maisonette": "A small house or an apartment on two floors.",
    "maunaloa": "One of the world's largest active volcanoes, located in Hawaii.",
    "hexastich": "A poem or stanza with six lines.",
    "bathypelagic": "Relating to the deep ocean zone where no light reaches.",
    "syzygy": "An alignment of three celestial bodies, like the sun, moon, and Earth.",
    "pharisaical": "Acting self-righteous or hypocritically pious.",
    "vicegerent": "A person acting as a deputy or representative of a ruler.",
    "pince-nez": "Eyeglasses that clip onto the nose without earpieces.",
    "carotid": "Related to the major arteries in the neck that supply blood to the head.",
    "salaam": "A greeting of peace used in Arabic and Muslim cultures.",
    "forzato": "A musical term meaning to play a note with sudden emphasis.",
    "covey": "A small group or flock, especially of birds like quail.",
    "apartheid": "A system of racial segregation that existed in South Africa.",
    "kibbutz": "A communal farm or settlement in Israel.",
    "putti": "Chubby cherubs or baby angels often seen in art.",
    "beignet": "A square French doughnut covered in powdered sugar.",
    "fricassee": "A dish of meat cut into pieces and cooked in a thick sauce.",
    "abecedarius": "A poem where each line starts with successive letters of the alphabet.",
    "collunarium": "A place where offerings to the gods are stored.",
    "scamillus": "A small platform or pedestal in classical architecture.",
    "buccinator": "The cheek muscle used for blowing and chewing.",
    "Tijuana": "A city in Mexico near the U.S. border.",
    "silenus": "A companion of the wine god Dionysus in Greek mythology.",
    "marcottage": "A method of plant reproduction by layering branches.",
    "schuss": "A straight, fast run down a ski slope.",
    "bodegon": "A Spanish still-life painting, often showing food.",
    "cri de coeur": "A passionate outcry or appeal from the heart.",
    "chaise longue": "A long chair for reclining, with a backrest at one end.",
    "tathagata": "A title for Buddha meaning 'one who has arrived at truth.'",
    "phalanstery": "A communal living building proposed by utopian thinkers.",
    "diapir": "A dome-shaped rock formation created by upward pressure.",
    "harmattan": "A dry, dusty wind that blows from the Sahara Desert.",
    "farinha": "A flour or meal made from cassava root, popular in Brazil.",
    "shamiana": "A large tent or canopy used for outdoor events in India.",
    "chautauqua": "An educational assembly popular in rural America in the 1800s.",
    "heishi": "Small shell beads used in Native American jewelry.",
    "mostaccioli": "Tube-shaped pasta with ridges, similar to penne.",
    "baetyl": "A sacred stone believed to house a deity.",
    "gardai": "Police officers in Ireland.",
    "gelinotte": "A type of game bird, also called a hazel grouse.",
    "zamacueca": "A South American dance with Spanish and African influences.",
    "geländesprung": "A skiing maneuver where you jump and turn while airborne.",
    "sittringee": "Striped cotton fabric from India."
};

export default DEFINITIONS;
